version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: gym_crm_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: gym_crm_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
      build: ../discovery-service
      container_name: eureka-server
      ports:
        - "8761:8761"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
        interval: 30s
        timeout: 10s
        retries: 3

  activemq:
    image: apache/activemq-classic:latest
    container_name: gym_crm_activemq
    ports:
      - "8161:8161"
      - "61616:61616"

  mongo:
    image: mongo:6.0
    container_name: gym_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  gym-crm:
    build: .
    container_name: gym_crm_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/gym_crm_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

    depends_on:
      postgres-db:
        condition: service_healthy
      activemq:
        condition: service_started

  workload-service:
    build: ../workload-service
    container_name: workload_app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/workload_db
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - mongo
      - activemq
      - eureka-server

volumes:
  mongo-data:
  postgres-data: