version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: gym_crm_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: gym_crm_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  activemq:
      image: apache/activemq-classic:latest
      container_name: gym_crm_activemq
      ports:
        - "8161:8161"
        - "61616:61616"

  mongo:
      image: mongo:6.0
      container_name: gym_mongo
      ports:
          - "27017:27017"
      volumes:
          - mongo-data:/data/db

volumes:
    mongo-data:
    postgres-data:
